import React, { useState, useEffect } from 'react';
import { DollarSign, PieChart, History, RefreshCw, Activity, TrendingUp, TrendingDown, BookOpen, Loader } from 'lucide-react';
import { apiPost } from '../App';

const TRADING_DISCLAIMER = `This module is for paper trading (simulated) and future live-order reference only.
No real capital is at risk. Live trading integration requires broker API keys to be configured
in Settings. All signals are generated by the quantitative pipeline and are informational only.`;

function LivePriceTicker({ tickers = ['SPX', 'BTC', 'GLD', 'WTI'] }) {
  const [prices, setPrices] = useState({});
  const [prevPrices, setPrevPrices] = useState({});

  useEffect(() => {
    const fetch1 = async () => {
      const results = {};
      await Promise.allSettled(tickers.map(async (t) => {
        try {
          const res = await fetch(`/api/chart/${t}`);
          if (res.ok) {
            const json = await res.json();
            const data = json.data || [];
            if (data.length >= 2) {
              results[t] = { close: data[data.length - 1].close, prev: data[data.length - 2].close };
            }
          }
        } catch (_) {}
      }));
      setPrevPrices(prev => ({ ...prev, ...Object.fromEntries(Object.entries(results).map(([k, v]) => [k, v.prev])) }));
      setPrices(Object.fromEntries(Object.entries(results).map(([k, v]) => [k, v.close])));
    };
    fetch1();
    const interval = setInterval(fetch1, 60000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
      {tickers.map(t => {
        const price = prices[t];
        const prev = prevPrices[t];
        const chg = price && prev ? ((price - prev) / prev) * 100 : null;
        const up = chg === null ? null : chg >= 0;
        return (
          <div key={t} style={{ flex: '1 1 110px', background: 'rgba(0,0,0,0.25)', borderRadius: '8px', padding: '10px 14px', border: `1px solid ${up === null ? 'rgba(184,245,66,0.08)' : up ? 'rgba(184,245,66,0.15)' : 'rgba(192,53,90,0.15)'}` }}>
            <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '4px', fontFamily: 'Space Grotesk' }}>{t}</p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: '1rem', fontWeight: 700, color: up === null ? 'var(--text-main)' : up ? 'var(--lime)' : 'var(--pink)', margin: 0 }}>
              {price ? `$${price.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—'}
            </p>
            {chg !== null && (
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: '0.75rem', color: up ? 'var(--lime-dim)' : 'var(--pink-deep)', margin: '2px 0 0 0', display: 'flex', alignItems: 'center', gap: '3px' }}>
                {up ? <TrendingUp size={10} /> : <TrendingDown size={10} />}
                {up ? '+' : ''}{chg.toFixed(2)}%
              </p>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function PaperTradingTab() {
  const [viewType, setViewType] = useState('live');
  const [triggerStatus, setTriggerStatus] = useState(null);
  const [data, setData] = useState({ portfolio: { cash: 10000.0, total_equity: 10000.0, positions: {} }, ledger: [] });
  const [nextUpdate, setNextUpdate] = useState(null);
  const [refreshing, setRefreshing] = useState(false);

  const fetchPortfolio = async (silent = true) => {
    if (!silent) setRefreshing(true);
    try {
      const res = await fetch(`/api/portfolio?type=${viewType}`);
      if (res.ok) {
        const json = await res.json();
        setData(json);
        const next = new Date();
        next.setHours(next.getHours() + 1, 0, 0, 0);
        setNextUpdate(next);
      }
    } catch (e) {
      console.error('Failed to fetch portfolio');
    } finally {
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchPortfolio();
    const interval = setInterval(() => fetchPortfolio(), 10000);
    return () => clearInterval(interval);
  }, [viewType]);

  const triggerBacktest = async () => {
    setTriggerStatus({ type: 'loading', msg: 'Running Simulation...' });
    try {
      const res = await apiPost('/api/trigger', { job: 'test' });
      if (res.ok) {
        setTriggerStatus({ type: 'ok', msg: 'Backtest triggered. Reload in ~30s.' });
        setTimeout(() => { setTriggerStatus(null); fetchPortfolio(); }, 35000);
      } else {
        const body = await res.json().catch(() => ({}));
        setTriggerStatus({ type: 'err', msg: `Failed: ${body.detail || res.status}` });
        setTimeout(() => setTriggerStatus(null), 6000);
      }
    } catch (e) {
      setTriggerStatus({ type: 'err', msg: `Error: ${e.message}` });
    }
  };

  const { portfolio, ledger } = data;
  const pnl = portfolio.total_equity - 10000.0;
  const pnlPct = (pnl / 10000.0) * 100;

  return (
    <div className="grid-layout">

      {/* Top bar */}
      <div className="glass-panel col-span-12" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}>
        <div style={{ display: 'flex', gap: '8px' }}>
          {[['live', 'Real-Time Mock Trading'], ['backtest', '6-Month Backtest']].map(([val, label]) => (
            <button key={val} onClick={() => setViewType(val)}
              style={{ padding: '8px 18px', borderRadius: '7px', border: `1px solid ${viewType === val ? 'var(--lime)' : 'rgba(184,245,66,0.12)'}`, background: viewType === val ? 'var(--gradient-primary)' : 'rgba(0,0,0,0.3)', color: viewType === val ? '#0a0b0f' : 'var(--lime)', cursor: 'pointer', fontSize: '0.85rem', fontWeight: 700, fontFamily: 'Space Grotesk', transition: 'all 0.2s' }}>
              {label}
            </button>
          ))}
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          {triggerStatus && (
            <span style={{ fontSize: '0.8rem', fontFamily: 'JetBrains Mono', color: triggerStatus.type === 'err' ? 'var(--pink)' : 'var(--lime)', display: 'flex', alignItems: 'center', gap: '6px' }}>
              {triggerStatus.type === 'loading' && <Loader size={12} style={{ animation: 'spin 1s linear infinite' }} />}
              {triggerStatus.msg}
            </span>
          )}

          <button className="btn-primary" onClick={() => fetchPortfolio(false)} disabled={refreshing}>
            {refreshing ? <Loader size={13} style={{ animation: 'spin 1s linear infinite' }} /> : <RefreshCw size={13} />}
            Refresh
          </button>

          {viewType === 'backtest' && (
            <button className="btn-danger" onClick={triggerBacktest}>
              <Activity size={13} /> Re-run Backtest
            </button>
          )}
        </div>
      </div>

      {/* Live Price Ticker — always show in live mode */}
      {viewType === 'live' && (
        <div className="glass-panel col-span-12 animate-fade-in delay-1">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px' }}>
            <h2 style={{ margin: 0 }}><TrendingUp size={17} style={{ color: 'var(--lime)' }} /> Live Price Feed</h2>
            {nextUpdate && (
              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', fontFamily: 'JetBrains Mono' }}>
                Daily update at {nextUpdate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
              </span>
            )}
          </div>
          <LivePriceTicker />
        </div>
      )}

      {/* Portfolio Summary */}
      <div className="glass-panel col-span-12 animate-fade-in delay-1">
        <h2><DollarSign size={17} style={{ color: 'var(--lime)' }} /> Portfolio Summary</h2>
        <div style={{ display: 'flex', gap: '36px', flexWrap: 'wrap' }}>
          <div>
            <p className="stat-label">Total Equity</p>
            <p className="stat-value">${portfolio.total_equity.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
          </div>
          <div>
            <p className="stat-label">Available Cash</p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: '2.4rem', fontWeight: 700, color: 'var(--lime)', marginTop: '4px' }}>
              ${portfolio.cash.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </p>
          </div>
          <div>
            <p className="stat-label">Total PnL</p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: '2.4rem', fontWeight: 700, color: pnl >= 0 ? 'var(--lime)' : 'var(--pink-deep)', marginTop: '4px', textShadow: `0 0 12px ${pnl >= 0 ? 'rgba(184,245,66,0.3)' : 'rgba(192,53,90,0.3)'}` }}>
              {pnl >= 0 ? '+' : ''}${Math.abs(pnl).toLocaleString(undefined, { minimumFractionDigits: 2 })} <span style={{ fontSize: '1.2rem' }}>({pnlPct.toFixed(2)}%)</span>
            </p>
          </div>
          {portfolio.win_rate !== undefined && (
            <div>
              <p className="stat-label">Win Rate</p>
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: '2.4rem', fontWeight: 700, color: portfolio.win_rate >= 50 ? 'var(--lime)' : 'var(--plasma-amber)', marginTop: '4px' }}>
                {portfolio.win_rate.toFixed(1)}%
              </p>
            </div>
          )}
          {portfolio.total_fees_paid !== undefined && (
            <div>
              <p className="stat-label">Slippage + Fees</p>
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: '2.4rem', fontWeight: 700, color: 'var(--plasma-amber)', marginTop: '4px' }}>
                ${portfolio.total_fees_paid.toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Open Positions */}
      <div className="data-panel col-span-6 animate-fade-in delay-2">
        <h2><PieChart size={17} style={{ color: 'var(--pink-soft)' }} /> Open Positions</h2>
        {Object.keys(portfolio.positions).length === 0 ? (
          <p className="text-muted" style={{ marginTop: '14px', fontFamily: 'JetBrains Mono', fontSize: '0.85rem' }}>No open positions — 100% Cash.</p>
        ) : (
          <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontFamily: 'JetBrains Mono', marginTop: '14px', fontSize: '0.85rem' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid rgba(184,245,66,0.1)' }}>
                <th style={{ padding: '10px 14px', color: 'var(--lime)', fontWeight: 600, fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Asset</th>
                <th style={{ padding: '10px 14px', color: 'var(--lime)', fontWeight: 600, fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Shares</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(portfolio.positions).map(([sym, shares]) => (
                <tr key={sym} className="data-item">
                  <td style={{ padding: '10px 14px', fontWeight: 700, color: '#fff' }}>{sym}</td>
                  <td style={{ padding: '10px 14px', color: 'var(--lime)' }}>{parseFloat(shares).toFixed(4)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Real Trading Reference Module */}
      <div className="data-panel col-span-6 animate-fade-in delay-2">
        <h2><BookOpen size={17} style={{ color: 'var(--lime-dim)' }} /> Live Trading Reference</h2>
        <div style={{ padding: '14px', background: 'rgba(184,245,66,0.04)', border: '1px solid rgba(184,245,66,0.1)', borderRadius: '8px', marginBottom: '14px' }}>
          <p style={{ fontFamily: 'JetBrains Mono', fontSize: '0.78rem', color: 'var(--lime-dim)', lineHeight: '1.65', whiteSpace: 'pre-wrap' }}>
            {TRADING_DISCLAIMER}
          </p>
        </div>
        <div style={{ fontFamily: 'JetBrains Mono', fontSize: '0.82rem' }}>
          {[
            ['Mode', 'Paper Simulation (No Real Orders)'],
            ['Live Broker API', 'Not configured'],
            ['Order Type', 'Market (next open)'],
            ['Data Source', 'Yahoo Finance / FRED'],
            ['Update Cadence', '1H context + 1D execution'],
          ].map(([k, v]) => (
            <div className="data-item" key={k}>
              <span className="text-muted">{k}</span>
              <span style={{ color: v.includes('Not') ? 'var(--plasma-amber)' : 'var(--lime-soft)' }}>{v}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Trade Ledger */}
      <div className="data-panel col-span-12 animate-fade-in delay-3">
        <h2><History size={17} style={{ color: 'var(--plasma-amber)' }} /> Mock Execution Ledger</h2>
        {ledger.length === 0 ? (
          <p className="text-muted" style={{ marginTop: '14px', fontFamily: 'JetBrains Mono', fontSize: '0.85rem' }}>No mock trades executed yet.</p>
        ) : (
          <div style={{ marginTop: '14px', overflowX: 'auto', maxHeight: '420px' }}>
            <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontFamily: 'JetBrains Mono', fontSize: '0.82rem' }}>
              <thead style={{ position: 'sticky', top: 0, background: 'rgba(10,11,15,0.96)', backdropFilter: 'blur(10px)', zIndex: 10 }}>
                <tr style={{ borderBottom: '1px solid rgba(184,245,66,0.1)' }}>
                  {['Time', 'Action', 'Asset', 'Shares', 'Price', 'Value', 'Stats'].map(col => (
                    <th key={col} style={{ padding: '10px 14px', color: 'var(--lime)', fontWeight: 600, fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {ledger.map((trade, i) => (
                  <tr key={i} className="data-item">
                    <td style={{ padding: '10px 14px', color: 'var(--text-muted)', fontSize: '0.78rem' }}>{new Date(trade.timestamp).toLocaleString()}</td>
                    <td style={{ padding: '10px 14px', fontWeight: 700, color: trade.action === 'BUY' ? 'var(--lime)' : 'var(--pink-deep)' }}>{trade.action}</td>
                    <td style={{ padding: '10px 14px', fontWeight: 700, color: '#fff' }}>{trade.ticker}</td>
                    <td style={{ padding: '10px 14px' }}>{parseFloat(trade.shares).toFixed(4)}</td>
                    <td style={{ padding: '10px 14px' }}>${parseFloat(trade.price).toFixed(2)}</td>
                    <td style={{ padding: '10px 14px' }}>${parseFloat(trade.value).toFixed(2)}</td>
                    <td style={{ padding: '10px 14px', color: 'var(--text-muted)', fontSize: '0.75rem' }}>{trade.stats || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <style>{`@keyframes spin { from{transform:rotate(0)} to{transform:rotate(360deg)} }`}</style>
    </div>
  );
}
