import React, { useState, useEffect } from 'react';
import { apiPost } from '../App';

const TRADING_DISCLAIMER = `This module is for paper trading (simulated) and future live-order reference only.
No real capital is at risk. Live trading integration requires broker API keys to be configured
in Settings. All signals are generated by the quantitative pipeline and are informational only.`;

function LivePriceTicker({ tickers = ['SPX', 'BTC', 'GLD', 'WTI'] }) {
  const [prices, setPrices] = useState({});
  const [prevPrices, setPrevPrices] = useState({});

  useEffect(() => {
    const fetch1 = async () => {
      const results = {};
      await Promise.allSettled(tickers.map(async (t) => {
        try {
          const res = await fetch(`/api/chart/${t}`);
          if (res.ok) {
            const json = await res.json();
            const data = json.data || [];
            if (data.length >= 2) {
              results[t] = { close: data[data.length - 1].close, prev: data[data.length - 2].close };
            }
          }
        } catch (_) {}
      }));
      setPrevPrices(prev => ({ ...prev, ...Object.fromEntries(Object.entries(results).map(([k, v]) => [k, v.prev])) }));
      setPrices(Object.fromEntries(Object.entries(results).map(([k, v]) => [k, v.close])));
    };
    fetch1();
    const interval = setInterval(fetch1, 60000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
      {tickers.map(t => {
        const price = prices[t];
        const prev = prevPrices[t];
        const chg = price && prev ? ((price - prev) / prev) * 100 : null;
        const up = chg === null ? null : chg >= 0;
        return (
          <div key={t} style={{ flex: '1 1 110px', background: 'var(--bg-panel)', padding: '6px 10px', border: `1px solid ${up === null ? 'var(--border-color)' : up ? 'var(--term-green)' : 'var(--term-red)'}` }}>
            <p style={{ fontSize: '10px', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '2px' }}>{t}</p>
            <p style={{ fontSize: '14px', fontWeight: 700, color: up === null ? 'var(--text-main)' : up ? 'var(--term-green)' : 'var(--term-red)', margin: 0 }}>
              {price ? `$${price.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—'}
            </p>
            {chg !== null && (
              <p style={{ fontSize: '10px', color: up ? 'var(--term-green)' : 'var(--term-red)', margin: '2px 0 0 0', display: 'flex', alignItems: 'center', gap: '3px' }}>
                {up ? '+' : ''}{chg.toFixed(2)}%
              </p>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function PaperTradingTab() {
  const [viewType, setViewType] = useState('live');
  const [triggerStatus, setTriggerStatus] = useState(null);
  const [data, setData] = useState({ portfolio: { cash: 10000.0, total_equity: 10000.0, positions: {} }, ledger: [] });
  const [nextUpdate, setNextUpdate] = useState(null);
  const [refreshing, setRefreshing] = useState(false);

  const fetchPortfolio = async (silent = true) => {
    if (!silent) setRefreshing(true);
    try {
      const res = await fetch(`/api/portfolio?type=${viewType}`);
      if (res.ok) {
        const json = await res.json();
        setData(json);
        const next = new Date();
        next.setHours(next.getHours() + 1, 0, 0, 0);
        setNextUpdate(next);
      }
    } catch (e) {
      console.error('Failed to fetch portfolio');
    } finally {
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchPortfolio();
    const interval = setInterval(() => fetchPortfolio(), 10000);
    return () => clearInterval(interval);
  }, [viewType]);

  const triggerBacktest = async () => {
    setTriggerStatus({ type: 'loading', msg: 'Running Simulation (~5 mins)...' });
    try {
      const res = await apiPost('/api/trigger', { job: 'test' });
      if (res.ok) {
        setTriggerStatus({ type: 'ok', msg: 'Backtest triggered. Please wait ~5 minutes and click Refresh.' });
        setTimeout(() => { setTriggerStatus(null); }, 15000); // Clear message after 15s
      } else {
        const body = await res.json().catch(() => ({}));
        setTriggerStatus({ type: 'err', msg: `Failed: ${body.detail || res.status}` });
        setTimeout(() => setTriggerStatus(null), 6000);
      }
    } catch (e) {
      setTriggerStatus({ type: 'err', msg: `Error: ${e.message}` });
    }
  };

  const { portfolio, ledger } = data;
  const pnl = portfolio.total_equity - 10000.0;
  const pnlPct = (pnl / 10000.0) * 100;

  return (
    <div className="grid-layout">

      {/* Top bar */}
      <div className="data-panel col-span-12" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px', padding: '4px 8px' }}>
        <div style={{ display: 'flex', gap: '4px' }}>
          {[['live', '[ REAL-TIME MOCK ]'], ['backtest', '[ 6-MONTH BACKTEST ]']].map(([val, label]) => (
            <button key={val} onClick={() => setViewType(val)}
              style={{ padding: '4px 8px', border: `1px solid ${viewType === val ? 'var(--term-green)' : 'var(--border-color)'}`, background: viewType === val ? 'var(--term-green)' : 'var(--bg-color)', color: viewType === val ? '#000' : 'var(--text-muted)', cursor: 'pointer' }}>
              {label}
            </button>
          ))}
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          {triggerStatus && (
            <span style={{ fontSize: '0.8rem', fontFamily: 'JetBrains Mono', color: triggerStatus.type === 'err' ? 'var(--pink)' : 'var(--lime)', display: 'flex', alignItems: 'center', gap: '6px' }}>

              {triggerStatus.msg}
            </span>
          )}

          <button onClick={() => fetchPortfolio(false)} disabled={refreshing}>
            [ REFRESH ]
          </button>

          {viewType === 'backtest' && (
            <button onClick={triggerBacktest} disabled={triggerStatus !== null} style={{ color: 'var(--term-cyan)', borderColor: 'var(--term-cyan)' }}>
              [ RE-RUN BACKTEST ]
            </button>
          )}
        </div>
      </div>

      {/* Live Price Ticker — always show in live mode */}
      {viewType === 'live' && (
        <div className="glass-panel col-span-12 animate-fade-in delay-1">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px' }}>
            <h2 style={{ margin: 0 }}> Live Price Feed</h2>
            {nextUpdate && (
              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', fontFamily: 'JetBrains Mono' }}>
                Daily update at {nextUpdate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
              </span>
            )}
          </div>
          <LivePriceTicker />
        </div>
      )}

      {/* Portfolio Summary */}
      <div className="data-panel col-span-12">
        <h2>[ PORTFOLIO SUMMARY ]</h2>
        <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', marginTop: '8px' }}>
          <div>
            <p className="stat-label">Total Equity</p>
            <p className="stat-value">${portfolio.total_equity.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
          </div>
          <div>
            <p className="stat-label">Available Cash</p>
            <p className="stat-value text-green">
              ${portfolio.cash.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </p>
          </div>
          <div>
            <p className="stat-label">Total PnL</p>
            <p className={`stat-value ${pnl >= 0 ? 'text-green' : 'text-red'}`}>
              {pnl >= 0 ? '+' : ''}${Math.abs(pnl).toLocaleString(undefined, { minimumFractionDigits: 2 })} <span style={{ fontSize: '10px' }}>({pnlPct.toFixed(2)}%)</span>
            </p>
          </div>
          {portfolio.realized_pnl !== undefined && (
            <div>
              <p className="stat-label">Realized PnL</p>
              <p className={`stat-value ${portfolio.realized_pnl >= 0 ? 'text-green' : 'text-red'}`}>
                {portfolio.realized_pnl >= 0 ? '+' : ''}${Math.abs(portfolio.realized_pnl).toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </p>
            </div>
          )}
          {portfolio.unrealized_pnl !== undefined && (
            <div>
              <p className="stat-label">Unrealized PnL</p>
              <p className={`stat-value ${portfolio.unrealized_pnl >= 0 ? 'text-green' : 'text-red'}`}>
                {portfolio.unrealized_pnl >= 0 ? '+' : ''}${Math.abs(portfolio.unrealized_pnl).toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </p>
            </div>
          )}
          {portfolio.win_rate !== undefined && (
            <div>
              <p className="stat-label">Active Win Rate</p>
              <p className={`stat-value ${portfolio.win_rate >= 50 ? 'text-green' : 'text-amber'}`}>
                {portfolio.win_rate.toFixed(1)}%
              </p>
              {portfolio.active_wins !== undefined && (
                <p style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
                  {portfolio.active_wins}W / {portfolio.active_losses}L / {portfolio.preservation_events}P
                </p>
              )}
            </div>
          )}
          {portfolio.total_fees_paid !== undefined && (
            <div>
              <p className="stat-label">Slippage + Fees</p>
              <p className="stat-value text-amber">
                ${portfolio.total_fees_paid.toLocaleString(undefined, { minimumFractionDigits: 2 })}
              </p>
            </div>
          )}
        </div>

        {/* New metrics row: Sharpe, Alpha, Max Drawdown, Benchmark */}
        {portfolio.sharpe_ratio !== undefined && (
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', marginTop: '12px', paddingTop: '12px', borderTop: '1px solid var(--border-color)' }}>
            <div>
              <p className="stat-label">Sharpe Ratio</p>
              <p className={`stat-value ${portfolio.sharpe_ratio >= 1.0 ? 'text-green' : portfolio.sharpe_ratio >= 0.5 ? 'text-amber' : 'text-red'}`}>
                {portfolio.sharpe_ratio.toFixed(2)}
              </p>
            </div>
            <div>
              <p className="stat-label">Alpha vs SPX</p>
              <p className={`stat-value ${portfolio.alpha_vs_spx >= 0 ? 'text-green' : 'text-red'}`}>
                {portfolio.alpha_vs_spx >= 0 ? '+' : ''}{portfolio.alpha_vs_spx.toFixed(2)}%
              </p>
            </div>
            <div>
              <p className="stat-label">Max Drawdown</p>
              <p className={`stat-value ${portfolio.max_drawdown <= 10 ? 'text-green' : portfolio.max_drawdown <= 20 ? 'text-amber' : 'text-red'}`}>
                {portfolio.max_drawdown.toFixed(1)}%
              </p>
            </div>
            <div>
              <p className="stat-label">SPX Benchmark</p>
              <p className="stat-value text-muted">
                {portfolio.benchmark_return >= 0 ? '+' : ''}{portfolio.benchmark_return.toFixed(2)}%
              </p>
            </div>
            {portfolio.circuit_breaker_count > 0 && (
              <div>
                <p className="stat-label">Circuit Breakers</p>
                <p className="stat-value text-red">
                  {portfolio.circuit_breaker_count}x
                </p>
              </div>
            )}
            {portfolio.conviction_blocks > 0 && (
              <div>
                <p className="stat-label">Conviction Blocks</p>
                <p className="stat-value text-purple">
                  {portfolio.conviction_blocks} bars
                </p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Open Positions */}
      <div className="data-panel col-span-6">
        <h2>[ OPEN POSITIONS ]</h2>
        {Object.keys(portfolio.positions).length === 0 ? (
          <p className="text-muted" style={{ marginTop: '14px', fontFamily: 'JetBrains Mono', fontSize: '0.85rem' }}>No open positions — 100% Cash.</p>
        ) : (
          <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontFamily: 'JetBrains Mono', marginTop: '14px', fontSize: '0.85rem' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid rgba(184,245,66,0.1)' }}>
                <th style={{ padding: '10px 14px', color: 'var(--lime)', fontWeight: 600, fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Asset</th>
                <th style={{ padding: '10px 14px', color: 'var(--lime)', fontWeight: 600, fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Shares</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(portfolio.positions).map(([sym, shares]) => (
                <tr key={sym} className="table-row-item">
                  <td style={{ padding: '10px 14px', fontWeight: 700, color: '#fff' }}>{sym}</td>
                  <td style={{ padding: '10px 14px', color: 'var(--lime)' }}>{parseFloat(shares).toFixed(4)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Real Trading Reference Module */}
      <div className="data-panel col-span-6">
        <h2>[ LIVE TRADING REFERENCE ]</h2>
        <div style={{ padding: '8px', border: '1px solid var(--term-amber)', marginBottom: '14px' }}>
          <p style={{ color: 'var(--term-amber)', lineHeight: '1.2', whiteSpace: 'pre-wrap', fontSize: '10px' }}>
            {TRADING_DISCLAIMER}
          </p>
        </div>
        <div>
          {[
            ['Mode', 'Paper Simulation (No Real Orders)'],
            ['Live Broker API', 'Not configured'],
            ['Order Type', 'Market (next open)'],
            ['Data Source', 'Yahoo Finance / FRED'],
            ['Update Cadence', '1H context + 1D execution'],
          ].map(([k, v]) => (
            <div className="data-item" key={k}>
              <span className="text-muted">{k}</span>
              <span className={v.includes('Not') ? 'text-amber' : 'text-main'}>{v}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Mock Execution Ledger */}
      <div className="data-panel col-span-12" style={{ maxHeight: '400px', overflowY: 'auto' }}>
        <h2>[ MOCK EXECUTION LEDGER ]</h2>
        {ledger.length === 0 ? (
          <p className="text-muted" style={{ marginTop: '14px', fontFamily: 'JetBrains Mono', fontSize: '0.85rem' }}>No mock trades executed yet.</p>
        ) : (
          <div style={{ marginTop: '14px', overflowX: 'auto', maxHeight: '420px' }}>
            <table>
            <thead style={{ position: 'sticky', top: 0, background: 'var(--bg-hover)', zIndex: 10 }}>
              <tr>
                {['Time', 'Action', 'Asset', 'Shares', 'Price', 'Value', 'Stats'].map(col => (
                  <th key={col}>{col}</th>
                ))}
              </tr>
            </thead>
            <tbody>
                {ledger.map((trade, i) => (
                  <tr key={i} className="table-row-item">
                    <td className="text-muted">{new Date(trade.timestamp).toLocaleString()}</td>
                    <td className={trade.action === 'BUY' ? 'text-green' : 'text-red'}>{trade.action}</td>
                    <td className="text-bright">{trade.ticker}</td>
                    <td>{parseFloat(trade.shares).toFixed(4)}</td>
                    <td>${parseFloat(trade.price).toFixed(2)}</td>
                    <td className="text-main">${parseFloat(trade.value).toFixed(2)}</td>
                    <td className="text-muted">
                      {trade.pnl !== undefined 
                        ? <span className={trade.pnl > 0 ? 'text-green' : trade.pnl < 0 ? 'text-red' : ''}>PnL: {trade.pnl > 0 ? '+' : ''}${parseFloat(trade.pnl).toFixed(2)}</span>
                        : trade.stats ? trade.stats : trade.fee ? `Fee: $${parseFloat(trade.fee).toFixed(2)}` : '-'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <style>{`@keyframes spin { from{transform:rotate(0)} to{transform:rotate(360deg)} }`}</style>
    </div>
  );
}
